### ISSUE TITLE
Permitir full-match nas tags para o delivery

### ISSUE THREAD

**Issue by andreyvital** [CotaPreco/Horus#11]
~~Não vou definir milestone, ou seja: pode ser que sim pode ser que não.~~

Pensei em introduzir um `TagSequencedMessage`, que é uma mensagem que irá conter uma sequência especifica de `Tag`s, que, no final das contas, irá significar entregar a mensagem pra todos que tenham exatamente as tags especificadas, ao invés de ter apenas uma das.

Pra não quebrar o _Receiver_ que já existe, pensei em incrementar o que poderia ser enviado nele, ficando o seguinte:

| payload | null-byte count |
| :-: | :-: |
| tag**\0**message | 1 |
| message | 0 |
| tag**\0\0**tag**\0\0**tag**\0**message | 5 |

E as invariantes:
- Nenhum **null-byte** é apenas mensagem;
- Um **null-byte** quer dizer essa mensagem pra todos que tem essa _tag_;
- Número de _null-byte_s deve ser ímpar no final de tudo, o que irá garantir tanto quando é apenas `tag\0message`, quanto a sequência.

**Comment by jucastilhoduarte** [comment]
Show :+1:
