### ISSUE TITLE
Não utilizar `os.Exit` pois dessa forma `deferred funcs` não executam

### ISSUE THREAD

**Issue by txgruppi** [CotaPreco/Horus#5]
Quando usando `os.Exit` o processo termina imediatamente, impedindo que `deferred funcs` sejam executadas.

O ideal é retornar o erro e fazer que esse erro chegue até 'quem' for responsável por tratar isso. `return` permite a execução de `deferred funcs`.

**Comment by andreyvital** [comment]
Sugestões? se eu tiver que tratar o erro no "owner"...I mean, no principal, `util.Invariant` perde o sentido, a ideia é quebrar se a condicional falhar!

Veja isso: https://groups.google.com/forum/#!topic/golang-nuts/UYoaWk6oJbY e isso: https://gist.github.com/philpennock/3948444

Algo interessante?

**Comment by txgruppi** [comment]
Eu não usaria `Invariant` e jogaria o erro pra cima no stack até chegar em quem tem capacidade de tratar, se o tratamento for parar que pare.

**Comment by andreyvital** [comment]
Pelos meus cálculos, o único **defer** que rola é o que [fecha a conexão do cidadão](https://github.com/CotaPreco/Horus/blob/b8641bbf8eabeb4badec14bb39d2233f3e2327dc/main.go#L56), considerando que falhe uma invariante, vai quitar tudo e de qualquer forma vai desligar o cara, não?

**Comment by txgruppi** [comment]
Despende se o `Close` precisa fazer algo antes de fechar.

**Comment by andreyvital** [comment]
Pelo visto, nada: https://github.com/gorilla/websocket/blob/master/conn.go#L201-L203. Apenas delega a call pra `net.Conn.Close`, ao menos aí.

**Comment by txgruppi** [comment]
Ainda acho que é melhor "fazer direito"

**Comment by andreyvital** [comment]
Que saiam os `Invariant`s então!

:beers:
