### ISSUE TITLE
Permitir caracteres especiais (/ ? @ : _ + *) na tag

### ISSUE THREAD

**Issue by jucastilhoduarte** [CotaPreco/Horus#8]

**Comment by andreyvital** [comment]
`Invariant Violation: ...invalid tag, `A tag should contains only `a-zA-Z0-9_-*:` 1..255` occurred while trying to receive`

Vou permitir qualquer caractere aceito em _querystring_, aí fica melhor.

**Comment by andreyvital** [comment]
@julianocomg acha que é melhor parar o serviço ou apenas ignorar a Tag inválida?

~eu~ voto em apenas ignorar, 1000 não precisam pagar o erro de 1 (nesse caso).

**Comment by jucastilhoduarte** [comment]
Ignora, bem melhor.
